### PR TITLE
Use `@wordpress/scripts`

### PR DESCRIPTION
**Pull request by ntwb**
Updates the repo to use `@wordpress/scripts`

### CODE REVIEW

**Comment by ntwb** [comment]
This PR is blocked by https://github.com/WordPress/gutenberg/issues/17061

**Comment by ntwb** [comment]
This PR is blocked by https://github.com/WordPress/gutenberg/pull/17060

**Comment by GaryJones** [comment]
For the uninitiated, can you please expand on what the `@wordpress/scripts` package is and why it should be switched to?

**Comment by ntwb** [comment]
This repo was still using the deprecated ESLint config, the replacement is [`@wordpress/eslint-plugin`](https://github.com/WordPress/gutenberg/tree/master/packages/eslint-plugin) so the vast majority of code in this PR is updated to adhere to the latest WordPress JS Coding Standards, which is what Gutenberg uses, as will WordPress Core.

The `@wordpress/scripts` package also includes this repo's styleint, Jest, npm-package-json-lint configs as dependencies which ship with a _default_ configuration, this _default_ configuration which is inherited allows for _zero configuration_ here in this repo. As such this repo removes any and all ESLint, stylelint, Jest, and npm-package-json-lint configurations greatly simplifying the configuration of the _build tools_ in the repo by not requiring any configuration whatsoever.

** There is one minor config tweak added in `.stylelintignore` here so that the stylelint Jest tests that are part of this repo run the stylelint tests using `stylelint-config-wordpress` against the valid CSS & SCSS test fixtures but ignore the invalid test fixtures.

**Comment by GaryJones** [comment]
Is it foreseeable that eventually there would be a `@wordpress/stylelint` or similar which would make this `stylelint-config-wordpress` redundant?

**Comment by ntwb** [comment]
Yes @GaryJones, this repo will be deprecated and moved to the Gutenberg _packages_ and become `@wordpress/stylelint-config`

See also: https://github.com/WordPress/gutenberg/pull/16924#issuecomment-518681192

**Pull request merged**
